// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Parse an entire EPUB and return all chapters as a JSON string.
Future<String> parseEpubToJson({required String path}) =>
    RustLib.instance.api.crateApiEpubApiParseEpubToJson(path: path);

/// Parse a single chapter by spine index and return as JSON string.
Future<String> parseChapterToJson({
  required String path,
  required BigInt chapterIndex,
}) => RustLib.instance.api.crateApiEpubApiParseChapterToJson(
  path: path,
  chapterIndex: chapterIndex,
);

/// Parse only metadata + TOC and return as JSON string.
Future<String> parseMetadataToJson({required String path}) =>
    RustLib.instance.api.crateApiEpubApiParseMetadataToJson(path: path);

/// Parse entire EPUB and export all chapters as individual JSON files.
///
/// Creates `out_dir/book.json` (metadata + toc + chapter_count)
/// and `out_dir/chapter_N.json` for each spine entry.
Future<String> batchExport({
  required String epubPath,
  required String outDir,
}) => RustLib.instance.api.crateApiEpubApiBatchExport(
  epubPath: epubPath,
  outDir: outDir,
);
